# Generated by Django 4.1 on 2022-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='eid',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='d_aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
