# Generated by Django 4.1 on 2022-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_patient_p_aadhar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="d_aadhar",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
    ]
