# Generated by Django 4.1 on 2022-11-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_remove_doctor_eid_alter_doctor_d_aadhar_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="p_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="p_state",
            new_name="state",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="pid",
        ),
    ]
