# Generated by Django 4.1 on 2022-11-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_doctor_d_aadhar_alter_doctor_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="p_aadhar",
            field=models.CharField(max_length=12),
        ),
    ]
